version: "3.8"

services:
  server:
    image: judge0/judge0:latest
    command: ["./scripts/server"]
    ports:
      - "2358:2358"
    environment:
      AUTH_DISABLE: "true"
      DOCKER_SIZE_LIMIT: "10GB"
      JUDGE0_HOST: 0.0.0.0
      JUDGE0_PORT: 2358
      DISABLE_SANDBOX: "true"
      USE_ISOLATE: "false"
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0
      POSTGRES_DB: judge0
    volumes:
      - ./isolate_job.rb:/api/app/jobs/isolate_job.rb
    depends_on:
      - postgres
      - redis
    restart: always

  workers:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    environment:
      AUTH_DISABLE: "true"
      DOCKER_SIZE_LIMIT: "10GB"
      JUDGE0_HOST: 0.0.0.0
      JUDGE0_PORT: 2358
      DISABLE_SANDBOX: "true"
      USE_ISOLATE: "false"
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0
      POSTGRES_DB: judge0
      WORKERS: 1
    volumes:
      - ./isolate_job.rb:/api/app/jobs/isolate_job.rb
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    privileged: true
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0
      POSTGRES_DB: judge0
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6
    restart: always

volumes:
  postgres-data:
